In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")

In [4]:
dataset = pd.get_dummies(dataset)

In [5]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [6]:
independent = dataset[['age','bmi','children','sex_female','sex_male','smoker_no','smoker_yes']]

In [7]:
independent

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0        True     False      False        True
1      18  33.770         1       False      True       True       False
2      28  33.000         3       False      True       True       False
3      33  22.705         0       False      True       True       False
4      32  28.880         0       False      True       True       False
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3       False      True       True       False
1334   18  31.920         0        True     False       True       False
1335   18  36.850         0        True     False       True       False
1336   21  25.800         0        True     False       True       False
1337   61  29.070         0        True     False      False        True

[1338 rows x 7 columns]

In [8]:
dependent = dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [10]:
x_train,x_test,y_train,y_test

(      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
 1163   18  28.215         0        True     False       True       False
 196    39  32.800         0        True     False       True       False
 438    52  46.750         5        True     False       True       False
 183    44  26.410         0        True     False       True       False
 1298   33  27.455         2       False      True       True       False
 ...   ...     ...       ...         ...       ...        ...         ...
 763    27  26.030         0       False      True       True       False
 835    42  35.970         2       False      True       True       False
 1216   40  25.080         0       False      True       True       False
 559    19  35.530         0       False      True       True       False
 684    33  18.500         1        True     False       True       False

 [936 rows x 7 columns],
       age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
 578    52  30.200         1       False      True       True       False
 610    47  29.370         1        True     False       True       False
 569    48  40.565         2       False      True      False        True
 1034   61  38.380         0       False      True       True       False
 198    51  18.050         0        True     False       True       False
 ...   ...     ...       ...         ...       ...        ...         ...
 1261   28  37.100         1       False      True       True       False
 494    21  25.700         4       False      True      False        True
 97     55  38.280         0       False      True       True       False
 418    64  39.160         1       False      True       True       False
 920    62  25.000         0        True     False       True       False

 [402 rows x 7 columns],
           charges
 1163   2200.83085
 196    5649.71500
 438   12592.53450
 183    7419.47790
 1298   5261.46945
 ...           ...
 763    3070.80870
 835    7160.33030
 1216   5415.66120
 559    1646.42970
 684    4766.02200

 [936 rows x 1 columns],
           charges
 578    9724.53000
 610    8547.69130
 569   45702.02235
 1034  12950.07120
 198    9644.25250
 ...           ...
 1261   3277.16100
 494   17942.10600
 97    10226.28420
 418   14418.28040
 920   13451.12200

 [402 rows x 1 columns])

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [12]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
from sklearn.svm import SVR

In [14]:
# Define parameter grid
# param_grid = {
#     'kernel': ['linear', 'rbf', 'poly'],
#     'C': [0.1, 1, 10, 100],
#     'epsilon': [0.01, 0.1, 0.5, 1],
#     'gamma': ['scale', 'auto']  # or numeric values like 0.01, 0.1, 1
# }

In [15]:
regressor = SVR(kernel='poly',C=100, epsilon=1, gamma=1)
regressor.fit(x_train,y_train)

C:\Users\PRAPANJANI\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100, epsilon=1, gamma=1, kernel='poly')

In [16]:
y_pred = regressor.predict(x_test)
y_pred

array([10022.22832328,  8734.61438758, 48704.94025856, 12592.81300835,
       10644.38386171,  4517.59804735,  1545.10957747, 11113.62137771,
        7302.22846394,  5269.73267477,  7005.54301419, 10271.81782381,
        7571.31915067,  4845.99514415, 25336.03485093, 10829.22359152,
       12361.51485493,  3218.66478285,  6470.54856577, 23776.46358429,
       26202.68187072, 12223.77228498,  9803.91111213, 31457.20669936,
        1811.91538862,  4541.83370398,  4525.86128441,  7831.30411821,
        4301.24596779,  8412.374404  ,  7854.17959323, 51984.47626522,
       13030.11947609, 10230.51772462, 12178.02276265,  4004.45278876,
        8755.11236426, 36545.89971394, 37562.65486561,  2049.67362742,
        6048.13883104,  3115.92642005, 27803.26151131, 44969.7983874 ,
       33776.96823849,  2923.64735495, 10839.92212621,  6985.00735836,
        4633.87278273, 12314.29117019,  2656.99433048,  2868.92662815,
       31790.15631196, 44719.4822741 , 11868.59236229,  2946.92790405,
        2565.28533201,  8647.58361365,  9581.05857892, 13112.3588618 ,
        1174.95204912, 34727.14860471, 14236.47810065,  9991.07950838,
       10312.18226218, 10018.22464759, 22359.18070156, 34261.79959128,
        2936.58627983,  7989.07176321, 13142.88829447, 11846.46692013,
       18720.73798263, 13882.07351488, 13004.71657326, 12775.87792728,
        7637.10725781,  8118.95454001, 25627.55154018, 45314.27921695,
       11232.50181043, 57542.07716983,  1777.51739734,  7796.89664058,
       41102.1565607 , 22934.48784462,  3856.94279636,  2511.13980317,
       12631.45118491, 36960.11209009,  5920.86969963, 10281.57116442,
        3206.25046369,  8673.53037676,  4193.81170418,  4814.8047448 ,
       37856.73550054, 33575.83127267,  5053.37634065, 10549.00636291,
        1967.37698629,  5419.33915648,  4394.40196076, 38734.47144591,
       29684.33640746,  3708.6985783 , 10969.84798714,  3617.65850606,
       11387.28762549, 41341.85246657, 12647.9934056 ,  4612.60860379,
        9048.0891432 , 23701.81504414, 53142.26969948,  7578.73574698,
        1988.36360751,  8640.77009332, 12672.99384995,  9299.06233157,
       40732.88372249, 10917.45723538, 14321.62598533,  5129.58275299,
        7904.32774927,  4969.26504756, 28137.08000575, 22374.39421455,
       51755.64041803,  1701.65515076,  8347.21735132,  1769.535435  ,
        6243.52995565,  9199.12215385, 34399.53552704, 32547.26423003,
       25901.28274136, 10442.19544371, 22618.09021086,  2528.46856402,
        2003.35540255, 10324.26614803,  9696.92475537,  9896.94627506,
        4951.26403753, 14303.96755868, 12837.59532785,  3316.2684261 ,
        1268.93875323, 10791.93213092,  6292.28158523, 43858.48574038,
        9686.32368214,  1626.75209078,  2515.35177429,  6762.47874018,
        2413.02758503,  1605.52101732, 10830.46542423,  9829.92490695,
        4408.89521719, 13000.68441314, 12868.25836422,  9685.74104308,
        4974.87611364,  4204.74357299, 11039.9947817 ,  5571.78579531,
        4225.18695564,  1981.8538606 ,  3975.83054975,  4091.86811459,
        8057.88753651,  2205.15041854,  4367.85753581,  4413.23844648,
        4183.08856537,  6374.13609544, 33386.2109889 ,   973.14688494,
       10815.5588105 ,  6720.47110768, 11001.60976847,  2734.62707606,
        5610.94882204, 31347.93841316,  1770.10029352,  2417.27084909,
       14296.32384044,  9847.45725128, 39050.67406177,  3889.23981856,
        5835.64164441, 26886.67961121,  2382.89255566,  2124.22444497,
        6216.7102192 ,  6132.58153097,  4478.44406073,  4219.77392995,
       10969.57601538, 42900.13358941, 11855.3358251 , 22261.86806146,
        4367.42138689, 44653.54720584,  3449.66439246,  9191.96663253,
        6053.16629648,  1246.02739302,  8711.47942357, 13466.50336752,
        4907.6640321 ,  2610.96200788,  6674.29126732,  2192.9132272 ,
        6472.42793882,  5340.07975495, 14023.01403517,  7453.2228194 ,
        6400.26337481,  7847.4990599 ,  8591.53595707,  3102.77100015,
       11887.18819631, 13915.93733146, 12270.73376691, 12151.19123508,
        7255.89931499,  2325.26920847,  1024.51229381,  8097.88660394,
       12263.417492  ,  3416.57262175,  4979.28476741,  7283.90581977,
        9092.57677328, 27228.88664149,  5892.04984578, 11422.19601737,
        5887.34311555, 29169.8397622 ,  7582.15636077,  7338.66964644,
        8346.58704008, 10369.79516898,  2603.98025673,  7581.72498145,
        2478.45321028,  6791.79375352, 27777.90267652, 36240.26697706,
        4007.86852342,  3667.32859388,  1557.69162279,  1022.73406498,
        7807.24919695,  1848.72146876,  4388.12032665,  3840.63665448,
        9312.93327441, 30670.96081743, 40068.41237769, 14537.51638709,
        6677.29857398, 10932.81820781, 43351.5574155 ,  9331.60822328,
       35953.88083327,  1145.82343636, 36540.20969547,  5094.92964442,
       12418.47185606,  3658.04076263, 38969.19464665,  5298.91931077,
        9554.27002568, 10255.35758022,  2074.69006563, 13222.7293549 ,
       12031.30377864,  4194.27179419, 12209.43057702,  1577.89143998,
        5930.53932501,  3583.1093168 ,  9230.90917848, 26339.146247  ,
        3145.03707932,   975.65674122,  2296.33424519, 43886.77755078,
        9088.07799304,  4609.61087255, 11860.5689071 , 11320.28339245,
       29095.09422642,  6809.1752581 ,  5149.67974132,  8510.58783931,
        1210.67960786,  2522.90112894,  8188.89142949, 20743.53170693,
       13494.94845302,  2316.89345439,  3325.96720978,  8955.92104119,
        9196.74576332, 10281.42287658, 25886.62636793,  6184.63575109,
       12894.19546579,  1776.05734034,  5509.77341976,  4193.11373616,
        8548.18332011,  2034.58992757,  6555.32594408, 48265.98766945,
        3208.72075898,  3743.63989792,  1886.59075222,  8516.45648188,
        3835.60532478, 12369.17745144, 39286.03687611, 17528.89511442,
        9026.34741038, 44340.24585615, 12597.22762788,  4375.22763145,
        9683.22820635,  3694.3340804 , 32914.78513786,  4802.06895234,
       13600.36643986,  1729.36671545, 16164.66843722,  3414.73369164,
       26144.14823966,  6084.63108152,  2182.75844953, 44562.27049895,
        5341.5816176 ,  5453.39839438, 32752.25484249,  1206.42371843,
        8369.42721576,  2216.55602262, 12205.15690884,  3914.66837485,
        5543.52188502,  5048.85939044, 42921.63238347,  8994.67865832,
       32156.31214949, 34186.54200921,  5890.04446896,  8822.67265927,
        1164.64305388,  3498.36576626,  2434.31766545,  8727.69467031,
       40917.91432201, 11228.81806299,  1781.4808943 , 11944.43928071,
        2323.31052505,  7643.07169961,  3783.05956645,  2037.9069852 ,
        3154.77383438, 31681.95684107,  7186.5044392 ,  1806.4787268 ,
       41916.25645498, 11095.53850666, 40510.36709376, 11634.47846821,
        4499.30776288,  2319.12996142,  1940.62859565, 10159.09370412,
        5156.88434383,  1633.11240729, 10296.50167621,  7335.74919399,
        6249.36680395,  3881.58091147,  2531.93189527, 38754.69572143,
        1580.51498269,  9373.75264068,  1910.13333204,  7386.49692016,
       10566.24479934,  3710.02526521, 16437.93104608, 10217.67758732,
       14836.60235694, 13718.74223217])

In [17]:
from sklearn.metrics import r2_score
rScore = r2_score(y_test,y_pred)

In [18]:
rScore

0.8576975692314952

#####

In [19]:
import pickle
filename = "finalized_model_svm.sav"
pickle.dump(regressor, open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict([[28, 29.215, 0, True, False, True, False]])
result

array([2208154.2386427])