In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [5]:
dependent = dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.3, random_state=0)
x_train, x_test, y_train, y_test

(      age     bmi  children  sex_male  smoker_yes
 1163   18  28.215         0     False       False
 196    39  32.800         0     False       False
 438    52  46.750         5     False       False
 183    44  26.410         0     False       False
 1298   33  27.455         2      True       False
 ...   ...     ...       ...       ...         ...
 763    27  26.030         0      True       False
 835    42  35.970         2      True       False
 1216   40  25.080         0      True       False
 559    19  35.530         0      True       False
 684    33  18.500         1     False       False

 [936 rows x 5 columns],
       age     bmi  children  sex_male  smoker_yes
 578    52  30.200         1      True       False
 610    47  29.370         1     False       False
 569    48  40.565         2      True        True
 1034   61  38.380         0      True       False
 198    51  18.050         0     False       False
 ...   ...     ...       ...       ...         ...
 1261   28  37.100         1      True       False
 494    21  25.700         4      True        True
 97     55  38.280         0      True       False
 418    64  39.160         1      True       False
 920    62  25.000         0     False       False

 [402 rows x 5 columns],
           charges
 1163   2200.83085
 196    5649.71500
 438   12592.53450
 183    7419.47790
 1298   5261.46945
 ...           ...
 763    3070.80870
 835    7160.33030
 1216   5415.66120
 559    1646.42970
 684    4766.02200

 [936 rows x 1 columns],
           charges
 578    9724.53000
 610    8547.69130
 569   45702.02235
 1034  12950.07120
 198    9644.25250
 ...           ...
 1261   3277.16100
 494   17942.10600
 97    10226.28420
 418   14418.28040
 920   13451.12200

 [402 rows x 1 columns])

In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=50, random_state = 0)
regressor.fit(x_train, y_train)

C:\Users\PRAPANJANI\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(n_estimators=50, random_state=0)

In [8]:
y_pred = regressor.predict(x_test)
y_pred

array([12282.2804522 ,  8764.113861  , 44772.9051962 , 12895.493955  ,
        9737.7968434 , 10955.5890496 ,  1819.923284  , 10999.7160492 ,
        7571.44975   ,  5243.259233  ,  7406.7301246 , 19822.828777  ,
       10287.765632  ,  6740.2823024 , 25051.403568  , 14198.6086778 ,
       14416.0292164 ,  3626.2247982 ,  6329.981364  , 33988.2161666 ,
       23823.764007  , 17011.9814798 , 11002.7722764 , 27190.196771  ,
        3559.3825378 ,  4980.9065606 ,  6295.6962992 ,  7870.2243036 ,
        3658.539715  ,  9452.3799872 ,  7960.8422032 , 48198.289067  ,
       13752.486407  , 11766.309958  , 16389.7241338 ,  4137.3677914 ,
        9075.5405382 , 37730.5435356 , 39510.883582  ,  2462.8122646 ,
        9275.6127334 ,  4681.573721  , 20358.856817  , 47698.916659  ,
       37265.4786356 ,  3849.7781506 , 14210.7521068 ,  6563.009295  ,
        4546.853408  , 12245.6690114 ,  4433.5777246 ,  4881.4242454 ,
       25420.38167   , 49374.6884792 , 11779.080324  , 10230.8462096 ,
        4036.3754946 ,  9508.3131918 , 10307.6815984 , 16779.8319452 ,
        1731.999767  , 46666.9131762 , 16019.6029908 , 20483.3366126 ,
       11048.7742908 ,  9869.57092   , 34341.6269634 , 40592.3357324 ,
        3346.0522208 , 10741.8831468 , 16996.7049448 , 11922.7722904 ,
       16916.8951942 , 13975.181435  , 13664.0343096 , 13944.1877238 ,
        7540.384563  , 15676.7712174 , 19417.802766  , 46663.312     ,
       11596.176888  , 48684.8362862 ,  5023.8141088 ,  9330.2090524 ,
       40877.9374428 , 19023.299318  ,  3200.589144  ,  3858.0400828 ,
       13654.5014306 , 39259.063888  ,  5759.6338502 , 13117.294054  ,
        2966.966899  , 10823.836921  ,  9164.2561026 ,  4164.506025  ,
       42757.469647  , 55011.1648542 ,  5460.6036994 , 11049.731035  ,
        3226.408778  ,  8961.9352114 ,  7144.3889652 , 40959.6636222 ,
       28308.0817704 ,  4957.818356  , 11275.775183  ,  6720.6196368 ,
       11603.339086  , 45353.287277  , 12365.1586878 ,  6130.8220542 ,
       10097.9338964 , 34530.1241156 , 47278.088634  ,  7218.7830246 ,
        2061.61742   ,  9608.3980128 , 22506.832271  ,  9513.2205388 ,
       41909.2982438 , 11665.719597  , 14587.869324  ,  9523.0347142 ,
       11316.080425  ,  4987.197985  , 26516.8605266 , 25831.8463808 ,
       48172.54466   ,  1553.779327  , 15783.6391064 ,  4897.3138892 ,
        6702.1927126 ,  9032.944797  , 45992.1654334 , 37836.4732418 ,
       24719.5401556 , 16751.4998818 , 24604.5756596 ,  6962.1851716 ,
        1983.888607  , 11379.4504706 , 10074.7056978 , 11074.360647  ,
        6822.8481104 , 14211.08538   , 23581.2879732 , 15350.824595  ,
        1521.359407  , 13409.8805958 ,  6210.128914  , 39302.5983188 ,
        9747.9304668 ,  9962.1723682 ,  2979.364563  ,  8871.214421  ,
        4540.0869412 ,  7542.3150194 , 14198.6086778 , 10282.082895  ,
        6216.2142728 , 13201.64993   , 13158.2150974 ,  9265.150902  ,
        4613.1416854 , 10135.0608282 , 16795.21319   ,  6714.5429894 ,
        4251.367229  ,  2061.902285  ,  5912.6890498 ,  6720.0685786 ,
       11608.888217  ,  2499.9291736 ,  9034.9103324 , 10538.8039792 ,
        4983.6243364 ,  6618.311343  , 26868.025664  ,  1661.709534  ,
       16617.5120364 ,  6880.443951  , 11420.070814  ,  7787.755306  ,
       10001.0738162 , 27882.350139  ,  5016.7389488 ,  3478.2794376 ,
       14125.065666  , 10844.9451216 , 41318.021328  ,  4049.568875  ,
        5362.702618  , 24975.8178862 ,  2889.6402516 ,  3260.9873746 ,
       10621.035459  ,  6562.8934398 , 11079.714028  ,  4344.728825  ,
       13273.7052484 , 46980.9255982 , 18283.5957952 , 18931.705708  ,
       11422.1073556 , 44394.0731234 ,  3782.3931734 , 10328.0083556 ,
        7691.8640064 ,  1977.151099  ,  9610.4726372 , 13633.31144   ,
        7339.9225126 ,  4591.7523286 ,  6502.40007   ,  9180.236278  ,
        6578.9926008 ,  5903.7416836 , 14055.296363  ,  6712.894318  ,
       13984.420613  ,  7809.017114  , 11312.1412864 ,  6091.2332156 ,
       14028.1296    , 14242.201371  , 21430.1331616 , 11975.732784  ,
        7355.0317284 ,  2948.3690704 , 11262.814406  ,  8088.032541  ,
       16054.892801  ,  6481.7605536 ,  5246.592878  ,  7144.050298  ,
       14738.9364338 , 34641.411652  ,  5887.606648  , 11937.555856  ,
        6232.2764414 , 37283.0584976 ,  8397.2531004 ,  7379.4962394 ,
       13472.5380762 , 10985.0939586 ,  3053.8235804 ,  8342.0326104 ,
        3132.1157026 ,  6477.599225  , 19322.202484  , 46323.103285  ,
        4206.46      ,  3023.761948  ,  7582.1323148 ,  2041.2423468 ,
        8142.2392068 ,  3196.9695325 , 10002.4003622 ,  9637.0580468 ,
        8857.7430588 , 24569.310278  , 45932.171488  , 17134.3094948 ,
        6552.409157  , 11269.144891  , 45071.5458994 ,  9567.4973848 ,
       39959.8990814 ,  1193.797392  , 37887.7153878 ,  5881.4110634 ,
       13034.3362178 ,  6948.1313464 , 40643.5989692 ,  6628.2419722 ,
       10501.8802974 , 10256.4341352 ,  3127.1420656 , 18187.0382226 ,
       12941.8171568 , 10543.107039  , 13437.9761416 , 15548.976099  ,
        7357.1024718 ,  6052.2504514 , 10476.7965554 , 21695.566951  ,
        3579.540189  ,  1649.876521  ,  2364.94158   , 47069.2127208 ,
       11020.0129954 ,  4338.8339744 , 16957.5317668 , 13621.567706  ,
       34679.6907888 ,  6789.782933  ,  5785.861026  ,  8856.910619  ,
        2614.1729246 ,  3637.0754666 , 22128.83086   , 16658.8775156 ,
       13751.4730062 ,  2974.9226964 ,  3302.069068  , 15384.7307002 ,
       11036.468837  , 15276.48055   , 20342.003318  , 11311.2138532 ,
       16881.9854814 ,  2046.699373  , 13612.742354  ,  8983.8336152 ,
       15327.659623  ,  2357.1683148 ,  6610.832282  , 46283.424006  ,
        3754.684193  ,  4626.4158774 ,  1894.916873  , 13391.316841  ,
        5889.3939686 , 12036.121569  , 46921.3640852 , 17773.252531  ,
        9075.956839  , 44690.60749   , 14292.5610164 , 11411.4827    ,
       11417.4886652 ,  6570.0122934 , 28326.110069  ,  4630.4686412 ,
       14415.920885  ,  2462.8558998 , 16488.453932  ,  3470.6779238 ,
       24675.377842  , 13353.655064  ,  5638.1065356 , 40262.8090562 ,
        6411.520638  ,  5263.534522  , 30436.7980932 ,  2427.6339434 ,
       11275.7965902 ,  4201.289004  , 12307.6982774 ,  3727.907539  ,
        8997.893981  ,  6269.6601354 , 46486.3874686 , 10144.2441016 ,
       48277.5831736 , 38400.3911442 ,  5902.115792  , 10512.031998  ,
        1531.727984  ,  5783.5641188 ,  2937.239906  , 10478.5424992 ,
       46514.6836062 , 11411.53798   ,  1959.053593  , 13189.357907  ,
        2084.573949  , 13576.2481824 ,  9234.2728562 ,  2422.317283  ,
        3833.7364102 , 36852.215352  ,  6607.096402  ,  1881.625218  ,
       41246.9001394 , 12455.191891  , 43937.8389364 , 11751.435707  ,
        8247.7998396 ,  3228.3283558 ,  2069.964868  , 17111.5218952 ,
        5268.6445696 ,  1881.979482  , 11431.2902178 ,  7228.060518  ,
        6063.713333  ,  5248.6942352 ,  8973.4319266 , 43041.2654674 ,
        5505.8629172 , 12473.2251272 ,  8086.61815067, 20197.5051658 ,
       11033.714903  ,  7709.6592502 , 17241.722005  , 11802.804586  ,
       19297.0130038 , 19431.0521804 ])

In [9]:
from sklearn.metrics import r2_score
rscore = r2_score(y_test, y_pred)
rscore

0.8498329315421834